# docker-compose -p backend_php up -d
version: '3.9'
services:
  nginx_dev:
    container_name: backend_php_nginx_dev
    image: 'nginx:alpine'
    restart: always
    working_dir: /app
    volumes:
      - '.:/app'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '30101:80'
    networks:
      dev:
      shared:
        aliases:
          - backend_php_nginx_dev
    depends_on:
      - app_dev
  nginx_prod:
    container_name: backend_php_nginx_prod
    image: 'nginx:alpine'
    restart: always
    working_dir: /app
    volumes:
      - '.:/app'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '30102:80'
    networks:
      prod:
      shared:
        aliases:
          - backend_php_nginx_prod
    depends_on:
      - app_prod
  app_dev:
    networks:
      dev:
        aliases:
          - app
    environment:
      APP_ENV: dev
    container_name: backend_php_app
    image: php:8.1.14-fpm-alpine
    restart: always
    working_dir: /app
    volumes:
      - '.:/app'
  app_prod:
    networks:
      prod:
        aliases:
          - app
    environment:
      APP_ENV: prod
    container_name: backend_php_app_prod
    image: php:8.1.14-fpm-alpine
    restart: always
    working_dir: /app
    volumes:
      - '.:/app'
networks:
  dev:
  prod:
  shared:
    external: true
    name: growthbook_shared
