parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\AppFeatureFlags:
        arguments: ["%kernel.cache_dir%/ff.json", '%env(GROWTHBOOK_WEBHOOK_SECRET)%', '%env(GROWTHBOOK_FEATURES_ENDPOINT)%']
        public: true
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
